obstacle_range: 3.0
raytrace_range: 3.0

footprint: [[0.30, 0.0], [0.30,-0.25], [0.0, -0.25], [-0.30, -0.25], [-0.30,0.0], [-0.30, 0.25], [0.0, 0.25], [0.30, 0.25]]
#robot_radius: 0.5
inflation_radius: 0.1

max_obstacle_height: 0.6
min_obstacle_height: 0.0

obstacle_layer:
   observation_sources: scan
   scan:
      data_type: LaserScan
      topic: scan
      marking: true
      clearing: true
      expected_update_rate: 0.0
      observation_persistence: 0.0

sonar_sensor_layer:
   ns: /sensors/sonar_sensor
   topics: ["sonar_two_range","sonar_four_range"]
   no_readings_timeout: 2.0
