global_costmap:
   map_type: costmap
   global_frame: /map1
   robot_base_frame: /base_link1
   update_frequency: 3.0
   publish_frequency: 3.0
   static_map: true
   rolling_window: false
   resolution: 0.1
   transform_tolerance: 5.0 
   track_unknown_space: true
   plugins: 
      - {name: static_map, type: "costmap_2d::StaticLayer"}
      - {name: obstacles, type: "costmap_2d::VoxelLayer"}
   static_map:
      map_topic: map1
   obstacles:
      observation_sources: base_scan
      base_scan: {data_type: LaserScan, sensor_frame: /base_laser1, clearing: true, marking: true, topic: /scan1}
