local_costmap:
   map_type: costmap
   global_frame: /odom1
   robot_base_frame: /base_link1
   update_frequency: 2.0
   publish_frequency: 2.0
   static_map: false
   rolling_window: true
   width: 4.0 
   height: 4.0
   resolution: 0.1
   transform_tolerance: 5.0
   track_unknown_space: true
   plugins:
     - {name: obstacles, type: "costmap_2d::VoxelLayer"}
     - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
   obstacles:
      observation_sources: base_scan
      base_scan: {data_type: LaserScan, sensor_frame: /base_laser1, clearing: true, marking: true, topic: /scan1}
