local_costmap:
   map_type: costmap
   global_frame: /odom1
   robot_base_frame: /base_link1
   update_frequency: 2.0
   publish_frequency: 2.0
   static_map: false
   rolling_window: true
   width: 2.0 
   height: 2.0
   resolution: 0.1
   transform_tolerance: 1.0
   plugins:
      - {name: obstacles, type: "costmap_2d::VoxelLayer"}
   obstacles:
      observation_sources: base_scan
      base_scan: {data_type: LaserScan, sensor_frame: /base_laser1, clearing: true, marking: true, topic: /scan1}
